# <strong>Student Data Book Archive</strong> {-}

<!-- {#archive} -->

# 2003-2017

## Data Book by Table Number: Fall 2017 {-}

## Data Book by Table Number: Fall 2016 {-}

## Data Book by Table Number: Fall 2015 {-}

## Data Book by Table Number: Fall 2014 {-}

## Data Book by Table Number: Fall 2013 {-}

## Data Book by Table Number: Fall 2012 {-}

## Data Book by Table Number: Fall 2011 {-}

## Data Book by Table Number: Fall 2010 {-}

## Data Book by Table Number: Fall 2009 {-}

## Data Book by Table Number: Fall 2008 {-}

## Data Book by Table Number: Fall 2007 {-}

## Data Book by Table Number: Fall 2006 {-}

## Data Book by Table Number: Fall 2005 {-}

## Data Book by Table Number: Fall 2004 {-}

## Data Book by Table Number: Fall 2003 {-}

# 1967-1998

## CUNY Data Book Fall 1998 {-}

## CUNY Data Book Fall 1997 {-}

## CUNY Data Book Fall 1996 {-}

## CUNY Data Book Fall 1995 {-}

## CUNY Data Book Fall 1994 {-}

## CUNY Data Book Fall 1993 {-}

## CUNY Data Book Fall 1992 {-}

## 1989-1991 Not Available {-}

## CUNY Data Book 1987-1988 {-}

## CUNY Data Book 1986-1987 {-}

## CUNY Data Book 1985-1986 {-}

## CUNY Data Book 1984-1985 {-}

## CUNY Data Book 1983-1984 {-}

## CUNY Data Book 1982-1983 {-}

## CUNY Data Book 1981-1982 {-}

## CUNY Data Book 1980-1981 {-}

## CUNY Data Book 1979-1980 {-}

## CUNY Data Book 1978-1979 {-}

## CUNY Data Book 1977-1978 {-}

## CUNY Data Book 1976-1977 {-}

## CUNY Data Book 1975-1976 {-}

## CUNY Data Book 1974-1975 {-}

## CUNY Data Book 1973-1974 {-}

## CUNY Data Book 1972-1973 {-}

## CUNY Data Book 1971-1972 {-}

## CUNY Data Book 1970-1971 {-}

## CUNY Data Book 1969-1970 {-}

## CUNY Data Book 1967-1968 {-}

